[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 -u scripts/run_live_bot.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[environments.production]
variables = {}
